---
# desktop.yml
- hosts: desktop
  name: Setup the Database and install confluence
  become: True

#   vars_prompt:
#     - name: "confluence_db_password"
#       prompt: "Enter the confluence users db password"
#       private: yes
# 
#     - name: "mysql_root_db_pass"
#       prompt: "Enter the root mysql users password"
#       private: yes

  vars_files: 
    - secrets.yml

  vars:
    - confluence_baseurl: "https://www.atlassian.com/software/confluence/downloads/binary"
    - confluence_version: 5.9.8
    - confluence_group: confluence
    - confluence_user: confluence
    - confluence_db: confluencedb
    - confluence_db_user: confluence
    - confluence_db_user_pass: "{{ secret_confluence_db_user_pass }}"
    - confluence_install_dir: "/opt/atlassian/confluence-{{ confluence_version }}"
    - confluence_base_dir: "/opt/atlassian/confluence"
    - confluence_home_dir: "/var/lib/confluence_home"
    - mysql_db:                                 
        - name: "{{ confluence_db }}"
    - mysql_users:                              
        - name: "{{ confluence_db_user }}"
          pass: "{{ confluence_db_user_pass }}"
          priv: "confluencedb.*"
          host: "localhost"


  roles:
#     - geerlingguy.java
    - bennojoy.mysql

  tasks:
    - name: install Confluence required packages
      apt:
        name: "{{ item }}"
        state: "{{ package_state }}"
      with_items:
        - python-lxml
        - openjdk-8-jdk

    - name: set basic facts
      set_fact:
        download_url: "{{ confluence_baseurl }}/atlassian-confluence-{{ confluence_version }}-x64.bin"
        download_tmp: "{{ confluence_home_dir }}/atlassian-confluence-{{ confluence_version }}-x64.bin"

    - name: create application group
      group: 
        name: "{{ confluence_group }}"
        system: no
        state: present

    - name: create user
      user: 
        name: "{{ confluence_user }}"
        system: no
        createhome: no
        comment: "Atlassian Confluence"
        group: "{{ confluence_group }}"
        home: "{{ confluence_home_dir }}"
        shell: /bin/false
        state: present

    - name: print directories
      debug:
        var: "{{ item }}"
      with_items:
        - confluence_base_dir
        - confluence_home_dir
        - confluence_install_dir

    - name: create directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items:
        - { path: "{{ confluence_base_dir }}",
            owner: 'root',
            group: 'root',
            mode: '0750' }
        - { path: "{{ confluence_home_dir }}",
            owner: "{{ confluence_user }}",
            group: "{{ confluence_group }}",
            mode: '0755' }
        - { path: "{{ confluence_install_dir }}",
            owner: 'root',
            group: 'root',
            mode: '0750' }

    - name: Pull down Confluence binary
      get_url:
#         url: https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-5.9.8-x64.bin
        url: "{{ download_url }}"
        dest: "{{ download_tmp }}"
        validate_certs: no
        force: no
