---
# desktop.yml
- hosts: desktop
  user: root
 
  vars:
    - clamav_clamtk_install: true
    - ntp_timezone: "US/Pacific"
    - vault_app: vault
    - vault_app_ver: '0.10.1'
    - vagrant_version: '2.2.0'
    - vault_app_checksums:
        linux_amd64: 031e521b4603487126fd353a9557dd22a02304a8a11f843e9914be59a8009c8a  
    - virtualbox_version : 5.2.20
    - ubuntu_version: cosmic


  roles:
#    - common
#     - ansible
#     - desktop
#     - virtualbox
#     - nvidia
#     - aws
#     - andrewrothstein.vault-app #failing
    - andrewrothstein.vagrant
    - andrewrothstein.packer
    - andrewrothstein.terraform
    - andrewrothstein.kubectl
    - andrewrothstein.minikube
      #    - andrewrothstein.virtualbox
      #     - keyboardinterrupt.sublime-text-3
#     - zoom
#     - webex #needs work
#     - keepass
    - telusdigital.ntp
    - dosullivan.kops
    - cmprescott.chrome
    - willshersystems.sshd
    - geerlingguy.docker
    - geerlingguy.ansible
#     - firefox-esr
#     - ansible-java8-oracle
    - wtanaka.gcloud-sdk
