---
# desktop.yml
- hosts: desktop
  user: root
 
  vars:
    - clamav_clamtk_install: true
    - ntp_timezone: "US/Pacific"
    - vault_app: vault
    - vault_app_ver: '0.10.1'
    - vault_app_checksums:
        linux_amd64: 031e521b4603487126fd353a9557dd22a02304a8a11f843e9914be59a8009c8a  
    - virtualbox_version : 5.2.12


  roles:
#    - common
#     - ansible
#     - desktop
#     - virtualbox
#     - nvidia
#     - aws
#     - andrewrothstein.vault-app #failing
    - andrewrothstein.vagrant
    - andrewrothstein.packer
    - andrewrothstein.terraform
    - andrewrothstein.kubectl
    - andrewrothstein.minikube
    - andrewrothstein.virtualbox
#     - zoom
# #     - logstash
#     - sssd-ad
#     - webex #needs work
#     - keepass
#     - igor_mukhin.clamav 
    - telusdigital.ntp
#     - pulse_client
#     - minikube
#     - docker_machine_kvm
    - dosullivan.kops
    - cmprescott.chrome
#    - suzuki-shunsuke.gcloud-ubuntu
    - willshersystems.sshd
    - geerlingguy.docker
    - geerlingguy.ansible
    - firefox-esr
    - ansible-java8-oracle
    - wtanaka.gcloud-sdk
