---
# desktop.yml
- hosts: desktop
  user: root
 
  vars:
    - clamav_clamtk_install: true
    - ntp_timezone: "US/Pacific"

  roles:
#    - common
#     - ansible
#     - desktop
#     - virtualbox
#     - nvidia
#     - aws
#     - andrewrothstein.vault-app
    - andrewrothstein.vagrant
    - andrewrothstein.packer
    - andrewrothstein.terraform
    - andrewrothstein.kubectl
    - andrewrothstein.minikube
#     - zoom
# #     - logstash
#     - sssd-ad
#     - webex #needs work
#     - keepass
#     - igor_mukhin.clamav 
    - telusdigital.ntp
#     - pulse_client
#     - minikube
#     - docker_machine_kvm
    - dosullivan.kops
    - cmprescott.chrome
#    - suzuki-shunsuke.gcloud-ubuntu
    - willshersystems.sshd
    - geerlingguy.docker
    - geerlingguy.ansible
#     - firefox-esr
#     - ansible-java8-oracle
    - wtanaka.gcloud-sdk
