---
# desktop.yml
- hosts: desktop
  user: root
  roles:
    - common
    - ansible
    - desktop
    - docker
    - virtualbox
    - vagrant
    - nvidia
    - aws
#    - kbrebanov.golang
    - packer
    - ateoto.terraform
#    - zoom
#    - logstash
    - mattwillsher.sshd
