---
# desktop.yml
- hosts: desktop
  user: root
 
  vars:
    - clamav_clamtk_install: true
    - ntp_timezone: "US/Pacific"

  roles:
    - common
    - ansible
    - desktop
    - docker
    - virtualbox
    - vagrant
    - nvidia
    - aws
    - packer
    - ateoto.terraform
    - zoom
# #     - logstash
    - mattwillsher.sshd
#     - geerlingguy.java
#     - sssd-ad
#     - webex #needs work
#     - keepass
#     - igor_mukhin.clamav 
    - telusdigital.ntp
#     - role-install-gcloud
    - pulse_client
    - minikube
#     - docker_machine_kvm
#     - dosullivan.kops
