- src: mattwillsher.sshd 

- src: geerlingguy.docker

- src: geerlingguy.ansible

- src: telusdigital.ntp

- src: andrewrothstein.vault-app
- src: andrewrothstein.kubectl
- src: andrewrothstein.minikube

- src: cmprescott.chrome
# - src: DataDog.ansible-datadog
