---
# roles/desktop/tasks/main.yml

- include: google_chrome.yml

- name: Install default desktop packages
  apt: pkg={{ item }}
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - gkrellm
    - gkrellm-x86info
    - vlc
    - git 
    - subversion 
    - git-doc
    - git-gui 
    - gitk 
    - git-svn 
    - subversion-tools
    - google-chrome-stable

- include: work_req.yml
