---
# roles/desktop/tasks/main.yml

- name: Include vars for the OS
  include_vars:


- name: Install default desktop packages
  apt: 
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:


- include: work_req.yml

- include: sublime.yml
