---
# roles/desktop/tasks/slack.yml

- name: Add slack deb repositiory
  apt_repository:
    repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
    state: present

- name: Install slack-desktop
  apt: 
    name: slack-desktop
    state: "{{ package_state }}"
