---
# roles/desktop/tasks/sublime.yml
# http://www.webupd8.org/2013/07/sublime-text-3-ubuntu-ppa-now-available.html

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Set up sources list file for sublime text editor
  apt_repository: 
    repo: deb https://download.sublimetext.com/ apt/stable/
  register: repo_change

- name: Apt update cache
  apt: update_cache=yes
  when: repo_change|success

- name: Install sublime text installer
  apt: 
    name: sublime-text-installer
    state: latest

