---
# roles/desktop/tasks/work_req.yml
- name: Install openvpn
  apt: 
    pkg: "{{ item }}"
    state: installed
  with_items:
    - freerdp
    - network-manager-openvpn

- include: hipchat.yml
- include: slack.yml
