---
# roles/vagrant/tasks/main.yml
- name: Check if vagrant is installed
  shell: dpkg -l vagrant | grep {{ vagrant_latest }}
  ignore_errors: True
  register: vagrant_check

- name: Download vagrant deb
  get_url: url=https://releases.hashicorp.com/vagrant/{{ vagrant_latest }}/vagrant_{{ vagrant_latest }}_x86_64.deb
           dest=/tmp/vagrant_{{ vagrant_latest }}_x86_64.deb
  when: vagrant_check|failed

- name: Install vagrant deb
  apt: deb=/tmp/vagrant_{{ vagrant_latest }}_x86_64.deb
  when: vagrant_check|failed
