galaxy_info:
  author: Daniel O'Sullivan
  description: A simple ansible role for installing kops.
  license: MIT

  min_ansible_version: 2.0
  platforms:
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Alpine
    versions:
    - all
  #  - any
  - name: EL
    versions:
    - all

  galaxy_tags:
    - kops
    - kubernetes

dependencies: []
