---
# ECS cli install
# http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_installation.html
# http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_Configuration.html

- name: Install ecs-cli tool
  get_url:
    url: https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
    dest: "{{ ecs_cli_binary }}"
    checksum: "{{ ecs_cli_binary_md5 }}"

- name: Set the permissions on the ecs_cli tool
  file: 
    path: "{{ ecs_cli_binary }}"
    owner: root
    group: root 
    mode: 0755
