---
# tasks file for aws

- name: Install required aws packages
  apt: name={{ item }}
       state=present
  with_items: "{{ aws_deb_packages }}"

- name: Install pip for pyplates packages
  apt: name=python-pip
       state=present

# https://github.com/seandst/cfn-pyplates
- name: pip install for pyplates
  apt: name=python-pip
       state=present

- name: Install pyplates
  pip: name=cfn-pyplates
       state=present
