---
# tasks file for aws

- name: Install required aws packages
  apt: name={{ item }}
       state=present
  with_items: "{{ aws_deb_packages }}"

- name: Install pip for extra python libraries
  apt: name=python-pip
       state=present

- name: Install aws pip packages
  pip: name={{ item }}
       state=present
  with_items: "{{ aws_pip_packages }}"
