---
# tasks file for sssd-ad

- name: Install required sssd packages
  package: 
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items: "{{ sssd_ad_apt_packages }}"

- name: Kerberos config file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644 

- name: Samba config file
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644 
  notify:
    - restart_smbd

- name: sssd config file
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600 
  notify:
    - restart_sssd

- name: NTP config file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644 
  notify:
    - restart_ntp
