---
# roles/virtualbox/tasks/main.yml
# https://www.virtualbox.org/wiki/Linux_Downloads

- name: Add the Virtualbox repo key
  apt_key: 
    url: "https://www.virtualbox.org/download/{{ item }}"
    state: present
  with_items:
    - oracle_vbox.asc
    - oracle_vbox_2016.asc

- name: Add Virtualbox repo file
  apt_repository: 
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ vb_ubuntu_distro }} contrib"
    filename: virtualbox.list
    state: present
    update_cache: yes

- name: Install dependencies for VirtualBox
  apt: 
    pkg: "{{ item }}"
    state: "{{ package_state }}"
  with_items: "{{ virtualbox_apt_packages }}"

# https://www.virtualbox.org/ticket/14445
- name: Retrieve compatible version of libvpx
  apt:
    deb: "http://{{ ubuntu_mirror}}/ubuntu/pool/main/libv/libvpx/libvpx2_1.4.0-4_amd64.deb"
    state: "{{ package_state }}"

- name: Install Virtualbox
  apt: 
    pkg: "virtualbox-{{ virtual_box_version }}"
    state: "{{ package_state }}"

# https://www.virtualbox.org/wiki/Downloads
# http://download.virtualbox.org/virtualbox/4.1.32/Oracle_VM_VirtualBox_Extension_Pack-4.1.34-95024.vbox-extpack
