---
# roles/ansible/tasks/main.yml
- name: Install software-properties-common
  apt:
    pkg: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - software-properties-common
    - python-apt
    - python-psycopg2
    - python-xmltodict
    - libkrb5-dev
    - python-httplib2
    - python3-httplib2
    - python-nose
    - python3-nose

- name: check to see if there is a ppa repository for your current ubuntu distro
  uri: 
    url: "http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/{{ ubuntu_distro }}"
  ignore_errors: True
  register: is_distro

- name: Add the ansible ppa
  apt_repository: 
    repo: 'ppa:ansible/ansible'
  when: is_distro|success

- name: Install the latest Ansible
  apt: 
    pkg: ansible
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: Ensure older apt versions of python modules are uninstalled
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - python-winrm
    - python3-winrm
    - pykerberos
    - pyYAML
    - jinja2
    - six

- name: Install later pip versions of python modules required for Ansible
  pip:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - pywinrm
    - azure
