---
# roles/ansible/tasks/main.yml
- name: Install software-properties-common
  apt: pkg={{ item }}
       state={{ package_state }}
  with_items:
    - software-properties-common
    - python-apt

- name: Add the ansible ppa
  apt_repository: repo='ppa:ansible/ansible'

- name: Install the latest Ansible
  apt: pkg=ansible
       update_cache=yes
       cache_valid_time=3600
       state=latest
