---
# defaults file for confluence

confluence_version: 5.9.7
confluence_archive_sha256sum: bff3b56a89ef277a03c6f9ff863194f1fe2b43ed5d8c5d92f319d90b55709469
confluence_jvm_minimum_memory: 1024m
confluence_jvm_maximum_memory: 1024m
