---
# vars file for confluence

confluence_archive: atlassian-confluence-{{ confluence_version }}.tar.gz
confluence_download_url: https://www.atlassian.com/software/confluence/downloads/binary/{{ confluence_archive }}
confluence_work_dir: /opt/atlassian
confluence_install_dir: /opt/atlassian/confluence
confluence_home_dir: /var/atlassian/application-data/confluence
