---

clamav_packages:
  - clamav # for manual usage
  - clamav-daemon # for running clamav as daemon
  # - clamav-freshclam # will installed anyway as dependency

# Update virus signatures database each time role runs
clamav_fresh: true

# Install ClamTk GUI
clamav_clamtk_install: true
