---
# roles/docker/tasks/main.yml
# http://docs.docker.com/engine/installation/ubuntulinux/

- name: Install apt-transport-https for docker
  apt: 
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ docker_required_apt_packages }}"

- name: Remove old docker repo key
  apt_key: 
    keyserver: "{{ ubuntu_apt_keyserver }}"
    id: "{{ docker_old_repo_key }}"
    state: absent

- name: Add the docker repo key
  apt_key: 
    keyserver: "{{ ubuntu_apt_keyserver }}"
    id: "{{ docker_repo_key }}"
    state: present

- name: Add Docker repo file
  copy: 
    content: "deb https://apt.dockerproject.org/repo ubuntu-{{ docker_ubuntu_distro }} main"
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: 0644

- name: Remove old Debian docker
  apt:
    pkg: lxc-docker
    state: absent

- name: Install docker docker deb
  apt: 
    pkg: "{{ item }}"
    state: "{{ package_state }}"
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - docker-engine
    - docker-compose

- name: Add a docker group
  group:
    name: docker
    state: present

- name: Enalble docker service to start on boot
  service: 
    name: docker
    enabled: yes
    state: started

