---
# roles/docker/tasks/main.yml
# https://docs.docker.com/installation/ubuntulinux/#ubuntu-trusty-1404-lts-64-bit

- name: Install apt-transport-https for docker
  apt: pkg=apt-transport-https
       update_cache=yes
       cache_valid_time=3600

- name: Add the docker repo key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80
           id=36A1D7869245C8950F966E92D8576A8BA88D21E9
           state=present

- name: Add Docker repo file
  copy: content="deb https://get.docker.io/ubuntu docker main"
        dest=/etc/apt/sources.list.d/docker.list
        owner=root
        group=root
        mode=644

- name: Install docker
  apt: pkg=lxc-docker
       state={{ package_state }}
       update_cache=yes
