---
# roles/docker/tasks/main.yml
# http://docs.docker.com/engine/installation/ubuntulinux/

- name: Install apt-transport-https for docker
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ docker_required_apt_packages }}"

- name: Remove old docker repo key
  apt_key:
    keyserver: "{{ ubuntu_apt_keyserver }}"
    id: "{{ item }}"
    state: absent
  with_items: "{{ docker_old_repo_key}}"

- name: Add the current docker repo key
  apt_key:
    keyserver: "{{ ubuntu_apt_keyserver }}"
    id: "{{ docker_repo_key }}"
    state: present

- name: remove old docker repo file
  file:
    name: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Add Docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ docker_ubuntu_distro }} stable"
    filename: docker-ubuntu.list
    state: present
  register: repo_change

- name: Remove old Debian docker
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - lxc-docker
    - docker
    - docker-compose

- name: Refresh apt cache with new repo
  apt:
    update_cache: yes
  when: repo_change|success

- name: Install docker docker deb
  apt:
    pkg: "{{ item }}"
    state: "{{ package_state }}"
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - docker-ce

- name: Add a docker group
  group:
    name: docker
    state: present

- name: Enalble docker service to start on boot
  service:
    name: docker
    enabled: yes
    state: started

- include: compose.yml
